baseURL = "http://yaotouge.github.io"
languageCode = "en-us"
title = "PetaBytes Studio"
theme = "hugo-xmin"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 4
[[menu.main]]
    name = "Tags"
    url = "/tags/"
    weight = 3
[[menu.main]]
    name = "Posts"
    url = "/posts/"
    weight = 2
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[params]
favicon="favicon.ico"